version: 1.0
data:
  n_jets: 8
  index_start: 0
  index_stop: null 
  mass_cut: 7000  # Mass cut in GeV
  path_dict: 'NEW_PATH_DICT_ATLAS_136_70'
  cross_section_dict: 'NEW_CROSS_SECTION_ATLAS_136_70'
  total_luminosity: 3000

cross_validation:
  enabled: true
  n_folds: 5

feature_extraction:
  n_jets: 8

preprocessing:
  scaler: 'minmax'  # Options: 'standard', 'minmax'
  test_size: 0.2
  random_state: 42
  oversample_signal: true

models:
  # neural_network:
  #   epochs: 5
  #   batch_size: 32
  #   learning_rate: 0.01
  #   layer_sizes: [64, 32, 32]
  #   dropout_rates: [0.2, 0.1]

  random_forest:
    n_estimators: 100
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42

  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    subsample: 1.0
    colsample_bytree: 1.0
    random_state: 42

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - roc_auc
    - average_precision
  evaluation:
    thresholds: [0.2, 0.5, 0.8, 0.90, 0.925, 0.95, 0.96, 0.97, 0.98, 0.99]
    use_real_event_percentiles: true  # Set to false to use raw event percentiles and true to use cross-section weighted event percentiles

visualization:
  plots:
    - roc_curve
    - pr_curve
    - feature_importances
    - sig_bkg_metrics

results:
  directory: 'jet_no_analysis/ATLAS_136_70_8j_5f' # 
  save_predictions: true
  save_feature_importances: true

logging:
  file_path: 'jet_no_analysis/ATLAS_136_70_8j_5f/experiment.log'
  level: 'INFO'