DATA_KEYS = [
    'BKG:gg_bbbar_2jets', 
    'BKG:gg_ccbar_2jets',
    'BKG:gg_gg_2jets',
    'BKG:qq_gg_2jets',
    'BKG:gg_qqbar_2jets',
    'BKG:qg_qg_2jets',
    'BKG:qqbar_bbbar_2jets',
    'BKG:qqbar_ccbar_2jets',
    'BKG:qq_qq_2jets',
    'BKG:qqbar_qqbarNew_2jets',
    'BKG:qg_Wjet_had',
    'BKG:qg_Wjet_lep',
    'BKG:qq_Wjet_had',
    'BKG:qq_Wjet_lep',
    'BKG:qq_hbbbar_had',
    'BKG:qq_hbbbar_lep',
    'BKG:gg_hbbbar_had',
    'BKG:gg_hbbbar_lep',
    'BKG:gg_ttbar_had',
    'BKG:gg_ttbar_lep',
    'BKG:qq_ttbar_had',
    'BKG:qq_ttbar_lep',
    'BKG:qq_WZ_had',
    'BKG:qq_WW_had',
    'BKG:qq_ZZ_had',
    'SIG:suu',
]

PATH_DICT = {
    'BKG:gg_bbbar_2jets': 'data/gg_bbar_2jets/gg_bbar_2jets_bckg.root',
    'BKG:gg_ccbar_2jets': 'data/gg_ccbar_2jet_bckg/gg_ccbar_2jet.root',
    'BKG:gg_gg_2jets': 'data/gg_gg_2jets/gg_gg_2jets_bckg.root',
    'BKG:qq_gg_2jets': 'data/qq_gg_2jets/qq_gg_2jets_bckg.root',
    'BKG:gg_qqbar_2jets': 'data/gg_qqbar_2jets/gg_qqbar_2jets_bckg.root',
    'BKG:qg_qg_2jets': 'data/qg_qg_2jets/qg_qg_2jets_bckg.root',
    'BKG:qqbar_bbbar_2jets': 'data/qqbar_bbar_2jets/qqbar_bbar_2jets_bckg.root',
    'BKG:qqbar_ccbar_2jets': 'data/qqbar_ccbar_2jet_bckg/qqbar_ccbar_2jet.root',
    'BKG:qq_qq_2jets': 'data/qq_qq_2jets_mhat7000/qq_qq_2jet_delphes_100kevents.root',
    'BKG:qqbar_qqbarNew_2jets': 'data/qqbar_qqbarNew_2jets/qqbar_qqbarNew_2jets_bckg.root',
    'BKG:qg_Wjet_had': 'data/qg_Wjet_hadronic_bckg/qg_Wj_hadronic_delphes_100kev.root',
    'BKG:qg_Wjet_lep': 'data/qg_Wjet_leptonic_bckg/qg_Wjet_letonic_delphes_100k.root',
    'BKG:qq_Wjet_had': 'data/qq_Wjet_hadronic_bckg/qqbar_Wj_hadronic_delphes_100kev.root',
    'BKG:qq_Wjet_lep': 'data/qq_Wjet_leptonic_bckg/qq_Wjet_letonic_delphes_100k.root',
    'BKG:qq_hbbbar_had': 'data/qq_hbbbar_hadronic_bckg/qq_hbbbar_hadronic_delphes_100k.root',
    'BKG:qq_hbbbar_lep': 'data/qq_hbbbar_leptonic_bckg/qq_hbbbar_leptonic_delphes_100k.root',
    'BKG:gg_hbbbar_had': 'data/gg_hbbbar_hadronic_bckg/gg_hbbbar_hadronic_delphes_100k.root',
    'BKG:gg_hbbbar_lep': 'data/gg_hbbbar_leptonic_bckg/gg_hbbbar_leptonic_delphes_100k.root',
    'BKG:gg_ttbar_had': 'data/gg_ttbar_hadronic_bckg/gg_ttbar_hadronic_delphes_100k.root',
    'BKG:gg_ttbar_lep': 'data/gg_ttbar_leptonic_bckg/gg_ttbar_leptonic_delphes_100k.root',
    'BKG:qq_ttbar_had': 'data/qq_ttbar_hadronic_bckg/qq_ttbar_hadronic_delphes_100k.root',
    'BKG:qq_ttbar_lep': 'data/qq_ttbar_leptonic_bckg/qq_ttbar_leptonic_delphes_100k.root',
    'BKG:qq_WZ_had': 'data/ff_ZW_delphes.root',
    'BKG:qq_WW_had': 'data/ff_WW_delphes.root',
    'BKG:qq_ZZ_had': 'data/ff_gmZgmZ_delphes.root',
    'SIG:suu': 'data/tag_1_delphes_events.root',
}

CROSS_SECTION_DICT = {
    'BKG:gg_bbbar_2jets': 2.348e-4,
    'BKG:gg_ccbar_2jets': 2.348e-3, 
    'BKG:gg_gg_2jets': 3.718e6,
    'BKG:qq_gg_2jets': 1.653e-1,
    'BKG:gg_qqbar_2jets': 2.130e-2,
    'BKG:qg_qg_2jets': 1.410e8 ,
    'BKG:qqbar_bbbar_2jets': 7.838e-6,
    'BKG:qqbar_ccbar_2jets': 7.827e-6,
    'BKG:qq_qq_2jets': 3.812e8,
    'BKG:qqbar_qqbarNew_2jets': 2.360e-5,
    'BKG:qg_Wjet_had': 4.329e-3,
    'BKG:qg_Wjet_lep': 2.070e-3,
    'BKG:qq_Wjet_had': 9.178e-4,
    'BKG:qq_Wjet_lep': 4.377e-4,
    'BKG:qq_hbbbar_had': 4.191e-12,
    'BKG:qq_hbbbar_lep': 9.590e-13,
    'BKG:gg_hbbbar_had': 3.204e-10,
    'BKG:gg_hbbbar_lep': 7.362e-11,
    'BKG:gg_ttbar_had': 2.881e-6,
    'BKG:gg_ttbar_lep': 6.610e-7,
    'BKG:qq_ttbar_had': 3.651e-6,
    'BKG:qq_ttbar_lep': 8.373e-7,
    'BKG:qq_WZ_had': 2.654e-6,
    'BKG:qq_WW_had': 1.090e-5,
    'BKG:qq_ZZ_had': 9.159e-7,
    'SIG:suu': 4.918e-5,
}

COLOR_DICT = {
    'BKG:gg_bbbar_2jets': '#21f0b6', 
    'BKG:gg_ccbar_2jets': '#b70d61',
    'BKG:gg_gg_2jets': '#60d11c',
    'BKG:qq_gg_2jets': '#922eb1',
    'BKG:gg_qqbar_2jets': '#c7e11f',
    'BKG:qg_qg_2jets': '#3f16f9',
    'BKG:qqbar_bbbar_2jets': '#699023',
    'BKG:qqbar_ccbar_2jets': '#fe74fe',
    'BKG:qq_qq_2jets': '#02531d',
    'BKG:qqbar_qqbarNew_2jets': '#fd6ca0',
    'BKG:qg_Wjet_had': '#54d7eb',
    'BKG:qg_Wjet_lep': '#7c2b2a',
    'BKG:qq_Wjet_had': '#aae3a4',
    'BKG:qq_Wjet_lep': '#1e438d',
    'BKG:qq_hbbbar_had': '#f7931e',
    'BKG:qq_hbbbar_lep': '#7e867b',
    'BKG:gg_hbbbar_had': '#b1c8eb',
    'BKG:gg_hbbbar_lep': '#e8250c',
    'BKG:gg_ttbar_had': '#2f937a',
    'BKG:gg_ttbar_lep': '#c57c89',
    'BKG:qq_ttbar_had': '#ebc30e',
    'BKG:qq_ttbar_lep': '#b69cfd',
    'BKG:qq_WZ_had': '#e6d3a5',
    'BKG:qq_WW_had': '#4787c9',
    'BKG:qq_ZZ_had': "#866609",
    'SIG:suu': "#000000",
}